/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License").
 * You may not use this file except in compliance with the License.
 * A copy of the License is located at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

package org.partiql.spi.function

/* ktlint-disable no-wildcard-imports */
import org.partiql.spi.catalog.Identifier
import org.partiql.spi.catalog.RoutineBinding
import org.partiql.spi.function.builtins.*
import org.partiql.spi.utils.FunctionUtils

/**
 * This is where we will register all SQL builtins; consider raising a "library" interface.
 *
 * TODO some cleanup efforts
 *  - make a libs folder
 *  - mv fn -> functions
 *  - organize builtins by type
 *  - add type families
 */
internal object Builtins {

    fun getFunctions(name: String): Collection<FnOverload> = functions[name] ?: emptyList()

    fun getAggregations(name: String): Collection<AggOverload> = aggregations[name] ?: emptyList()

    fun resolveFunctions(identifier: Identifier): Collection<RoutineBinding<FnOverload>> =
        registry.resolveFunctions(identifier)

    fun resolveAggregations(identifier: Identifier): Collection<RoutineBinding<AggOverload>> =
        registry.resolveAggregations(identifier)

    private val functions = listOf<FnOverload>(
        Fn_ABS__INT8__INT8,
        Fn_ABS__INT16__INT16,
        Fn_ABS__INT32__INT32,
        Fn_ABS__INT64__INT64,
        Fn_ABS__NUMERIC__NUMERIC,
        Fn_ABS__FLOAT32__FLOAT32,
        Fn_ABS__FLOAT64__FLOAT64,
        Fn_ABS__DECIMAL_ARBITRARY__DECIMAL_ARBITRARY,
        Fn_ABS__INTERVAL_YM__INTERVAL_YM,
        Fn_ABS__INTERVAL_DT__INTERVAL_DT,
        Fn_AND__BOOL_BOOL__BOOL,
        FnBetween,
        FnOverlaps,
        Fn_BIT_LENGTH__STRING__INT32,
        Fn_BIT_LENGTH__CLOB__INT32,
        FnBitwiseAnd,
        Fn_CARDINALITY__BAG__INT32,
        Fn_CARDINALITY__LIST__INT32,
        Fn_CARDINALITY__STRUCT__INT32,
        Fn_CARDINALITY__MAP__INT32,
        Fn_CHAR_LENGTH__STRING__INT,
        Fn_CHAR_LENGTH__CLOB__INT,

        Fn_COLL_AGG__BAG__ANY.ANY_ALL,
        Fn_COLL_AGG__BAG__ANY.AVG_ALL,
        Fn_COLL_AGG__BAG__ANY.COUNT_ALL,
        Fn_COLL_AGG__BAG__ANY.EVERY_ALL,
        Fn_COLL_AGG__BAG__ANY.MAX_ALL,
        Fn_COLL_AGG__BAG__ANY.MIN_ALL,
        Fn_COLL_AGG__BAG__ANY.SOME_ALL,
        Fn_COLL_AGG__BAG__ANY.SUM_ALL,
        Fn_COLL_AGG__BAG__ANY.ANY_DISTINCT,
        Fn_COLL_AGG__BAG__ANY.AVG_DISTINCT,
        Fn_COLL_AGG__BAG__ANY.COUNT_DISTINCT,
        Fn_COLL_AGG__BAG__ANY.EVERY_DISTINCT,
        Fn_COLL_AGG__BAG__ANY.MAX_DISTINCT,
        Fn_COLL_AGG__BAG__ANY.MIN_DISTINCT,
        Fn_COLL_AGG__BAG__ANY.SOME_DISTINCT,
        Fn_COLL_AGG__BAG__ANY.SUM_DISTINCT,
        FnConcat,

        Fn_CURRENT_DATE____DATE,
        Fn_CURRENT_USER____STRING,
        Fn_DATE_ADD_DAY__INT32_DATE__DATE,
        Fn_DATE_ADD_DAY__INT32_TIMESTAMP__TIMESTAMP,
        Fn_DATE_ADD_DAY__INT64_DATE__DATE,
        Fn_DATE_ADD_DAY__INT64_TIMESTAMP__TIMESTAMP,
        Fn_DATE_ADD_HOUR__INT32_TIME__TIME,
        Fn_DATE_ADD_HOUR__INT32_TIMESTAMP__TIMESTAMP,
        Fn_DATE_ADD_HOUR__INT64_TIME__TIME,
        Fn_DATE_ADD_HOUR__INT64_TIMESTAMP__TIMESTAMP,
        Fn_DATE_ADD_MINUTE__INT32_TIME__TIME,
        Fn_DATE_ADD_MINUTE__INT32_TIMESTAMP__TIMESTAMP,
        Fn_DATE_ADD_MINUTE__INT64_TIME__TIME,
        Fn_DATE_ADD_MINUTE__INT64_TIMESTAMP__TIMESTAMP,
        Fn_DATE_ADD_MONTH__INT32_DATE__DATE,
        Fn_DATE_ADD_MONTH__INT32_TIMESTAMP__TIMESTAMP,
        Fn_DATE_ADD_MONTH__INT64_DATE__DATE,
        Fn_DATE_ADD_MONTH__INT64_TIMESTAMP__TIMESTAMP,
        Fn_DATE_ADD_SECOND__INT32_TIME__TIME,
        Fn_DATE_ADD_SECOND__INT32_TIMESTAMP__TIMESTAMP,
        Fn_DATE_ADD_SECOND__INT64_TIME__TIME,
        Fn_DATE_ADD_SECOND__INT64_TIMESTAMP__TIMESTAMP,
        Fn_DATE_ADD_YEAR__INT32_DATE__DATE,
        Fn_DATE_ADD_YEAR__INT32_TIMESTAMP__TIMESTAMP,
        Fn_DATE_ADD_YEAR__INT64_DATE__DATE,
        Fn_DATE_ADD_YEAR__INT64_TIMESTAMP__TIMESTAMP,
        Fn_DATE_DIFF_DAY__DATE_DATE__INT64,
        Fn_DATE_DIFF_DAY__TIMESTAMP_TIMESTAMP__INT64,
        Fn_DATE_DIFF_DAY__TIMESTAMPZ_TIMESTAMPZ__INT64,
        Fn_DATE_DIFF_HOUR__TIME_TIME__INT64,
        Fn_DATE_DIFF_HOUR__TIMEZ_TIMEZ__INT64,
        Fn_DATE_DIFF_HOUR__TIMESTAMP_TIMESTAMP__INT64,
        Fn_DATE_DIFF_HOUR__TIMESTAMPZ_TIMESTAMPZ__INT64,
        Fn_DATE_DIFF_MINUTE__TIME_TIME__INT64,
        Fn_DATE_DIFF_MINUTE__TIMEZ_TIMEZ__INT64,
        Fn_DATE_DIFF_MINUTE__TIMESTAMP_TIMESTAMP__INT64,
        Fn_DATE_DIFF_MINUTE__TIMESTAMPZ_TIMESTAMPZ__INT64,
        Fn_DATE_DIFF_SECOND__TIME_TIME__INT64,
        Fn_DATE_DIFF_SECOND__TIMEZ_TIMEZ__INT64,
        Fn_DATE_DIFF_SECOND__TIMESTAMP_TIMESTAMP__INT64,
        Fn_DATE_DIFF_SECOND__TIMESTAMPZ_TIMESTAMPZ__INT64,
        Fn_DATE_DIFF_YEAR__DATE_DATE__INT64,
        Fn_DATE_DIFF_YEAR__TIMESTAMP_TIMESTAMP__INT64,
        Fn_DATE_DIFF_YEAR__TIMESTAMPZ_TIMESTAMPZ__INT64,
        Fn_DATE_DIFF_MONTH__DATE_DATE__INT64,
        Fn_DATE_DIFF_MONTH__TIMESTAMP_TIMESTAMP__INT64,
        Fn_DATE_DIFF_MONTH__TIMESTAMPZ_TIMESTAMPZ__INT64,
        FnDivide,
        FnEq,
        Fn_EXTRACT_DAY__DATE__INT32,
        Fn_EXTRACT_DAY__TIMESTAMP__INT32,
        Fn_EXTRACT_DAY__INTERVAL__INT32,
        Fn_EXTRACT_HOUR__TIME__INT32,
        Fn_EXTRACT_HOUR__TIMESTAMP__INT32,
        Fn_EXTRACT_HOUR__INTERVAL__INT32,
        Fn_EXTRACT_MINUTE__TIME__INT32,
        Fn_EXTRACT_MINUTE__TIMESTAMP__INT32,
        Fn_EXTRACT_MINUTE__INTERVAL__INT32,
        Fn_EXTRACT_MONTH__DATE__INT32,
        Fn_EXTRACT_MONTH__TIMESTAMP__INT32,
        Fn_EXTRACT_MONTH__INTERVAL__INT32,
        Fn_EXTRACT_SECOND__TIME__DECIMAL_ARBITRARY,
        Fn_EXTRACT_SECOND__TIMESTAMP__DECIMAL_ARBITRARY,
        Fn_EXTRACT_SECOND__INTERVAL__DECIMAL_ARBITRARY,
        Fn_EXTRACT_TIMEZONE_HOUR__TIME__INT32,
        Fn_EXTRACT_TIMEZONE_HOUR__TIMESTAMP__INT32,
        Fn_EXTRACT_TIMEZONE_MINUTE__TIME__INT32,
        Fn_EXTRACT_TIMEZONE_MINUTE__TIMESTAMP__INT32,
        Fn_EXTRACT_YEAR__DATE__INT32,
        Fn_EXTRACT_YEAR__TIMESTAMP__INT32,
        Fn_EXTRACT_YEAR__INTERVAL__INT32,
        FnGt,
        FnGte,
        FnInCollection,
        FnSqlInCollection,

        Fn_IS_TRUE__ANY__BOOL,
        Fn_IS_FALSE__ANY__BOOL,
        Fn_IS_UNKNOWN__ANY__BOOL,

        Fn_IS_ANY__ANY__BOOL,
        Fn_IS_BAG__ANY__BOOL,
        Fn_IS_BINARY__ANY__BOOL,
        Fn_IS_BLOB__ANY__BOOL,
        Fn_IS_BOOL__ANY__BOOL,
        Fn_IS_BYTE__ANY__BOOL,
        Fn_IS_CHAR__INT32_ANY__BOOL,
        Fn_IS_CHAR__ANY__BOOL,
        Fn_IS_CLOB__ANY__BOOL,
        Fn_IS_DATE__ANY__BOOL,
        Fn_IS_DECIMAL__INT32_INT32_ANY__BOOL,
        Fn_IS_DECIMAL__ANY__BOOL,
        Fn_IS_FLOAT32__ANY__BOOL,
        Fn_IS_FLOAT64__ANY__BOOL,
        Fn_IS_INT__ANY__BOOL,
        Fn_IS_INT16__ANY__BOOL,
        Fn_IS_INT32__ANY__BOOL,
        Fn_IS_INT64__ANY__BOOL,
        Fn_IS_INT8__ANY__BOOL,
        Fn_IS_INTERVAL__ANY__BOOL,
        Fn_IS_LIST__ANY__BOOL,
        Fn_IS_MAP__ANY__BOOL,
        Fn_IS_MISSING__ANY__BOOL,
        Fn_IS_NULL__ANY__BOOL,

        Fn_IS_STRING__INT32_ANY__BOOL,
        Fn_IS_STRING__ANY__BOOL,
        Fn_IS_STRUCT__ANY__BOOL,

        Fn_IS_TIME__BOOL_INT32_ANY__BOOL,
        Fn_IS_TIME__ANY__BOOL,
        Fn_IS_TIMESTAMP__BOOL_INT32_ANY__BOOL,
        Fn_IS_TIMESTAMP__ANY__BOOL,

        FnLike,
        FnLikeEscape,

        FnLower,

        FnLt,
        FnLte,
        FnMinus,
        FnModulo,
        Fn_NEG__INT8__INT8,
        Fn_NEG__INT16__INT16,
        Fn_NEG__INT32__INT32,
        Fn_NEG__INT64__INT64,
        Fn_NEG__INT__INT,
        Fn_NEG__FLOAT32__FLOAT32,
        Fn_NEG__FLOAT64__FLOAT64,
        Fn_NEG__DECIMAL_ARBITRARY__DECIMAL_ARBITRARY,
        Fn_NOT__BOOL__BOOL,
        Fn_OR__BOOL_BOOL__BOOL,
        Fn_OCTET_LENGTH__STRING__INT32,
        Fn_OCTET_LENGTH__CLOB__INT32,
        FnPlus,
        Fn_POS__INT8__INT8,
        Fn_POS__INT16__INT16,
        Fn_POS__INT32__INT32,
        Fn_POS__INT64__INT64,
        Fn_POS__INT__INT,
        Fn_POS__FLOAT32__FLOAT32,
        Fn_POS__FLOAT64__FLOAT64,
        Fn_POS__DECIMAL_ARBITRARY__DECIMAL_ARBITRARY,
        Fn_POSITION__STRING_STRING__INT64,
        Fn_POSITION__CLOB_CLOB__INT64,

        Fn_SUBSTRING__STRING_INT32__STRING,
        Fn_SUBSTRING__STRING_INT32_INT32__STRING,
        Fn_SUBSTRING__CLOB_INT64__CLOB,
        Fn_SUBSTRING__CLOB_INT64_INT64__CLOB,

        FnTimes,
        FnTrim,

        Fn_TRIM_CHARS__STRING_STRING__STRING,
        Fn_TRIM_CHARS__CLOB_CLOB__CLOB,

        Fn_TRIM_LEADING__STRING__STRING,
        Fn_TRIM_LEADING__CLOB__CLOB,

        Fn_TRIM_LEADING_CHARS__STRING_STRING__STRING,
        Fn_TRIM_LEADING_CHARS__CLOB_CLOB__CLOB,

        Fn_TRIM_TRAILING__STRING__STRING,
        Fn_TRIM_TRAILING__CLOB__CLOB,

        Fn_TRIM_TRAILING_CHARS__STRING_STRING__STRING,
        Fn_TRIM_TRAILING_CHARS__CLOB_CLOB__CLOB,

        FnUpper,

        Fn_UTCNOW____TIMESTAMP,
        //
        // NON SQL FUNCTIONS
        //
        Fn_EXISTS__BAG__BOOL,
        Fn_EXISTS__LIST__BOOL,
        Fn_EXISTS__STRUCT__BOOL,
        Fn_EXISTS__MAP__BOOL,
        Fn_SIZE__BAG__INT32,
        Fn_SIZE__LIST__INT32,
        Fn_SIZE__STRUCT__INT32,
        Fn_SIZE__MAP__INT32,

        Fn_MAP_KEYS__MAP__BAG,
        Fn_MAP_VALUES__MAP__BAG,
        Fn_MAP_ENTRIES__MAP__BAG,
        FnMapContainsKey,
        FnMapGet,

        FnReplace,
        FnSplit,
    ).groupBy { it.signature.name }

    @JvmStatic
    private val aggregations: Map<String, List<AggOverload>> = listOf<AggOverload>(
        Agg_ANY__BOOL__BOOL,
        Agg_AVG__INT8__INT8,
        Agg_AVG__INT16__INT16,
        Agg_AVG__INT32__INT32,
        Agg_AVG__INT64__INT64,
        Agg_AVG__NUMERIC__NUMERIC,
        Agg_AVG__DECIMAL_ARBITRARY__DECIMAL_ARBITRARY,
        Agg_AVG__FLOAT32__FLOAT32,
        Agg_AVG__FLOAT64__FLOAT64,
        Agg_AVG__ANY__ANY,
        Agg_COUNT__ANY__INT64,
        Agg_EVERY__BOOL__BOOL,
        Agg_EVERY__ANY__BOOL,
        Agg_MAX__INT8__INT8,
        Agg_MAX__INT16__INT16,
        Agg_MAX__INT32__INT32,
        Agg_MAX__INT64__INT64,
        Agg_MAX__NUMERIC__NUMERIC,
        Agg_MAX__DECIMAL_ARBITRARY__DECIMAL_ARBITRARY,
        Agg_MAX__FLOAT32__FLOAT32,
        Agg_MAX__FLOAT64__FLOAT64,
        Agg_MAX__ANY__ANY,
        Agg_MIN__INT8__INT8,
        Agg_MIN__INT16__INT16,
        Agg_MIN__INT32__INT32,
        Agg_MIN__INT64__INT64,
        Agg_MIN__INT__INT,
        Agg_MIN__DECIMAL_ARBITRARY__DECIMAL_ARBITRARY,
        Agg_MIN__FLOAT32__FLOAT32,
        Agg_MIN__FLOAT64__FLOAT64,
        Agg_MIN__ANY__ANY,
        Agg_SOME__BOOL__BOOL,
        Agg_SOME__ANY__BOOL,
        Agg_SUM__INT8__INT8,
        Agg_SUM__INT16__INT16,
        Agg_SUM__INT32__INT32,
        Agg_SUM__INT64__INT64,
        Agg_SUM__NUMERIC__NUMERIC,
        Agg_SUM__DECIMAL_ARBITRARY__DECIMAL_ARBITRARY,
        Agg_SUM__FLOAT32__FLOAT32,
        Agg_SUM__FLOAT64__FLOAT64,
        Agg_SUM__ANY__ANY,
        Agg_GROUP_AS__ANY__ANY
    ).groupBy { it.signature.name }

    private val hiddenRoutineNames = mapOf(
        FunctionUtils.hide("and") to "and",
        FunctionUtils.hide("between") to "between",
        FunctionUtils.hide("bitwise_and") to "bitwise_and",
        FunctionUtils.hide("coll_any_all") to "coll_any_all",
        FunctionUtils.hide("coll_any_distinct") to "coll_any_distinct",
        FunctionUtils.hide("coll_avg_all") to "coll_avg_all",
        FunctionUtils.hide("coll_avg_distinct") to "coll_avg_distinct",
        FunctionUtils.hide("coll_count_all") to "coll_count_all",
        FunctionUtils.hide("coll_count_distinct") to "coll_count_distinct",
        FunctionUtils.hide("coll_every_all") to "coll_every_all",
        FunctionUtils.hide("coll_every_distinct") to "coll_every_distinct",
        FunctionUtils.hide("coll_max_all") to "coll_max_all",
        FunctionUtils.hide("coll_max_distinct") to "coll_max_distinct",
        FunctionUtils.hide("coll_min_all") to "coll_min_all",
        FunctionUtils.hide("coll_min_distinct") to "coll_min_distinct",
        FunctionUtils.hide("coll_some_all") to "coll_some_all",
        FunctionUtils.hide("coll_some_distinct") to "coll_some_distinct",
        FunctionUtils.hide("coll_sum_all") to "coll_sum_all",
        FunctionUtils.hide("coll_sum_distinct") to "coll_sum_distinct",
        FunctionUtils.hide("concat") to "concat",
        FunctionUtils.hide("current_date") to "current_date",
        FunctionUtils.hide("current_user") to "current_user",
        FunctionUtils.hide("date_add_day") to "date_add_day",
        FunctionUtils.hide("date_add_hour") to "date_add_hour",
        FunctionUtils.hide("date_add_minute") to "date_add_minute",
        FunctionUtils.hide("date_add_month") to "date_add_month",
        FunctionUtils.hide("date_add_second") to "date_add_second",
        FunctionUtils.hide("date_add_year") to "date_add_year",
        FunctionUtils.hide("date_diff_day") to "date_diff_day",
        FunctionUtils.hide("date_diff_hour") to "date_diff_hour",
        FunctionUtils.hide("date_diff_minute") to "date_diff_minute",
        FunctionUtils.hide("date_diff_month") to "date_diff_month",
        FunctionUtils.hide("date_diff_second") to "date_diff_second",
        FunctionUtils.hide("date_diff_year") to "date_diff_year",
        FunctionUtils.hide("divide") to "divide",
        FunctionUtils.hide("eq") to "eq",
        FunctionUtils.hide("extract_day") to "extract_day",
        FunctionUtils.hide("extract_hour") to "extract_hour",
        FunctionUtils.hide("extract_minute") to "extract_minute",
        FunctionUtils.hide("extract_month") to "extract_month",
        FunctionUtils.hide("extract_second") to "extract_second",
        FunctionUtils.hide("extract_timezone_hour") to "extract_timezone_hour",
        FunctionUtils.hide("extract_timezone_minute") to "extract_timezone_minute",
        FunctionUtils.hide("extract_year") to "extract_year",
        FunctionUtils.hide("gt") to "gt",
        FunctionUtils.hide("gte") to "gte",
        FunctionUtils.hide("in_collection") to "in_collection",
        FunctionUtils.hide("is_any") to "is_any",
        FunctionUtils.hide("is_bag") to "is_bag",
        FunctionUtils.hide("is_binary") to "is_binary",
        FunctionUtils.hide("is_blob") to "is_blob",
        FunctionUtils.hide("is_bool") to "is_bool",
        FunctionUtils.hide("is_byte") to "is_byte",
        FunctionUtils.hide("is_char") to "is_char",
        FunctionUtils.hide("is_clob") to "is_clob",
        FunctionUtils.hide("is_date") to "is_date",
        FunctionUtils.hide("is_decimal") to "is_decimal",
        FunctionUtils.hide("is_false") to "is_false",
        FunctionUtils.hide("is_float32") to "is_float32",
        FunctionUtils.hide("is_float64") to "is_float64",
        FunctionUtils.hide("is_int") to "is_int",
        FunctionUtils.hide("is_int16") to "is_int16",
        FunctionUtils.hide("is_int32") to "is_int32",
        FunctionUtils.hide("is_int64") to "is_int64",
        FunctionUtils.hide("is_int8") to "is_int8",
        FunctionUtils.hide("is_interval") to "is_interval",
        FunctionUtils.hide("is_list") to "is_list",
        FunctionUtils.hide("is_map") to "is_map",
        FunctionUtils.hide("is_missing") to "is_missing",
        FunctionUtils.hide("is_null") to "is_null",
        FunctionUtils.hide("is_string") to "is_string",
        FunctionUtils.hide("is_struct") to "is_struct",
        FunctionUtils.hide("is_time") to "is_time",
        FunctionUtils.hide("is_timestamp") to "is_timestamp",
        FunctionUtils.hide("is_true") to "is_true",
        FunctionUtils.hide("is_unknown") to "is_unknown",
        FunctionUtils.hide("like") to "like",
        FunctionUtils.hide("like_escape") to "like_escape",
        FunctionUtils.hide("lt") to "lt",
        FunctionUtils.hide("lte") to "lte",
        FunctionUtils.hide("minus") to "minus",
        FunctionUtils.hide("neg") to "neg",
        FunctionUtils.hide("not") to "not",
        FunctionUtils.hide("or") to "or",
        FunctionUtils.hide("overlaps") to "overlaps",
        FunctionUtils.hide("plus") to "plus",
        FunctionUtils.hide("pos") to "pos",
        FunctionUtils.hide("position") to "position",
        FunctionUtils.hide("sql_in_collection") to "sql_in_collection",
        FunctionUtils.hide("times") to "times",
        FunctionUtils.hide("trim") to "trim",
        FunctionUtils.hide("trim_chars") to "trim_chars",
        FunctionUtils.hide("trim_leading") to "trim_leading",
        FunctionUtils.hide("trim_leading_chars") to "trim_leading_chars",
        FunctionUtils.hide("trim_trailing") to "trim_trailing",
        FunctionUtils.hide("trim_trailing_chars") to "trim_trailing_chars",
    )

    private val registry = BuiltinRoutineRegistry(functions, aggregations, hiddenRoutineNames)
}
